### ISSUE TITLE
Problem with tensorflow 0.11, Attempting to use uninitialized value

### ISSUE THREAD

**Issue by HenryCaiHaiying** [OlavHN/fast-neural-style#10]
Error as below when running in tensorflow 0.11.

Based on https://github.com/tensorflow/tensorflow/issues/3168, the workaround is to make sure we don't use unitialized variables.

hcai@logging-tf-cpu-1:/mnt/hcai/tf/fast-neural-style$ python fast_neural_style.py  --STYLE_IMAGES ../neural-style/examples/1-style.jpg --BATCH_SIZE 4
New model initilized
Done training -- epoch limit reached
Traceback (most recent call last):
  File "fast_neural_style.py", line 172, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "fast_neural_style.py", line 169, in main
    coord.join(threads)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 386, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner.py", line 225, in _run
    sess.run(enqueue_op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 717, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 915, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 985, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.FailedPreconditionError: Attempting to use uninitialized value input_producer/limit_epochs/epochs
     [[Node: input_producer/limit_epochs/CountUpTo = CountUpTo[T=DT_INT64, _class=["loc:@input_producer/limit_epochs/epochs"], limit=2, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer/limit_epochs/epochs)]]

**Comment by OlavHN** [comment]
Hi!

Now using `initialize_local_variables()`

Thanks!
